#=============
# === nord powerline angled ===
#=============

"$schema" = 'https://starship.rs/config-schema.json'

# === Main Prompt Format ===
format = """
$os\
$username\
[î‚°](fg:#2e3440 bg:#5e81ac)\
$hostname\
[î‚°](fg:#5e81ac bg:#81a1c1)\
$directory\
[î‚°](fg:#81a1c1 bg:#88c0d0)\
$git_branch\
$git_status\
[î‚°](fg:#88c0d0 bg:#8fbcbb)\
$python\
[î‚°](fg:#8fbcbb bg:#d9dee9)\
$cmd_duration\
[î‚°](fg:#d9dee9 bg:#88c0d0)\
$jobs\
[î‚°](fg:#88c0d0 bg:#5e81ac)\
$time\
\n$character
"""

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#2e3440 fg:#d8dee9"
format = '[$user ]($style)'

[hostname]
ssh_only = false
format = "[$ssh_symbol@$hostname]($style)"
ssh_symbol = "î¬ "
style = "bg:#5e81ac fg:#2e3440"

[os]
disabled = false
style = "bg:#2e3440 fg:#d8dee9"

[os.symbols]
Arch = 'ïŒƒ '
Ubuntu = "ó°•ˆ"
Macos = "î˜Ÿ"
Linux = "ó°Œ½"

[directory]
style = "bg:#81a1c1 fg:#2e3440"
read_only = "î©µ"
read_only_style = "bg:#81a1c1 fg:#2e3440 bold"
format = "[ ó°‰‹ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï’˜"
"Music" = "ó°š"
"Pictures" = "ï€¾"

[git_branch]
symbol = "ó°˜¬ "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:#88c0d0 fg:#2e3440"

[git_status]
style = "bg:#88c0d0 fg:#2e3440 bold"
format = "[ $all_status$ahead_behind ]($style)"
conflicted = "âš¡$count"
ahead      = "â‡¡$count"
behind     = "â‡£$count"
diverged   = "â§–$count"
untracked  = "â€¦$count"
stashed    = "ğŸ“¦$count"
modified   = "âœ$count"
staged     = "âœ”$count"
renamed    = "âœ$count"
deleted    = "âœ–$count"

[python]
symbol = 'ó°Œ  '
format = "[ $symbol$virtualenv ]($style)"
style = "bg:#8fbcbb fg:#2e3440"

[cmd_duration]
disabled = false
# ms
min_time = 3000
format = "[ ó°”š $duration ]($style)"
style = "bg:#d9dee9 fg:#2e3440"

[jobs]
disabled = false
format = "[ $symbol$number ]($style)"
style = "bg:#88c0d0 fg:#2e3440"

[time]
disabled = false
format = "[ ïº $time ]($style)[î‚°](fg:#5e81ac bg:#2e3440)"
style = "bg:#5e81ac fg:#2e3440"
time_format = "%H:%M"

[character]
success_symbol = "[ï²](bold fg:#a3be8c)"
error_symbol   = "[ï²](bold fg:#bf616a)"

vimcmd_symbol = "[ î˜« ï²](bold fg:#a3be8c)"
vimcmd_replace_one_symbol = "[ î˜« ï´](bold fg:#ebcb8b)"
vimcmd_replace_symbol = "[ î˜« ï´](bold fg:#d08770)"
vimcmd_visual_symbol = "[ î˜« ï´](bold fg:#b48ead)"
