#=============
# === nord ===
#=============

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](#5e81ac)\
$os$username[@](bg:#5e81ac fg:#2e3440)$hostname\
[î‚°](bg:#81a1c1 fg:#5e81ac)\
$directory\
[î‚°](bg:#88c0d0 fg:#81a1c1)\
$git_branch$git_status\
[î‚°](bg:#8fbcbb fg:#88c0d0)\
$python$direnv\
[î‚°](bg:#d9dee9 fg:#8fbcbb)\
$cmd_duration\
[î‚°](fg:#d9dee9)\
$fill\
(bg:#88c0d0 fg:#d9dee9)\
$jobs\
(bg:#5e81ac fg:#88c0d0)\
$time\
(fg:#5e81ac)\
$line_break\
$character
"""


[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "ó°˜¬ "
style = "fg:#2e3440 bg:#88c0d0"

[git_status]
style = "fg:#2e3440 bg:#88c0d0 bold"
format = "[ $all_status$ahead_behind ]($style)"
conflicted = "âš¡$count "      # conflicts
ahead      = "â‡¡$count "      # commits ahead
behind     = "â‡£$count "      # commits behind
diverged   = "â§–$count "      # diverged branch
untracked  = "â€¦$count "      # untracked files
stashed    = "ğŸ“¦$count "     # stash (Nerd Font box)
modified   = "âœ$count "      # modified
staged     = "âœ”$count "      # staged
renamed    = "âœ$count "      # renamed
deleted    = "âœ–$count "      # deleted

[python]
symbol = 'ó°Œ  '
format = "[ $symbol($virtualenv )]($style)"
style = "fg:#2e3440 bg:#8fbcbb"

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#5e81ac"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = "î¬ "

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

[os.symbols]
Arch = 'ïŒƒ '
Ubuntu = "ó°•ˆ"
Macos = "î˜Ÿ"
Linux = "ó°Œ½"

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[directory]
style = "fg:#2e3440 bg:#81a1c1"
read_only = "î©µ "
format = "[ ó°‰‹ $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[cmd_duration]
min_time = 2
format = "[ ó°”š $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[character]
success_symbol = "[ï²](bold fg:#a3be8c)"
error_symbol   = "[ï²](bold fg:#bf616a)"

vimcmd_symbol = "[ î˜« ï²](bold fg:#a3be8c)"
vimcmd_replace_one_symbol = "[ î˜« ï´](bold fg:#ebcb8b)"
vimcmd_replace_symbol = "[ î˜« ï´](bold fg:#d08770)"
vimcmd_visual_symbol = "[ î˜« ï´](bold fg:#b48ead)"

[direnv]
disabled = true
format = "[ $symbol$loaded ]($style)"
style = 'fg:#2e3440 bg:#8fbcbb'

[jobs]
disabled = false
format = "(bg:#88c0d0 fg:#d9dee9)[ $symbol$number ]($style)(bg:#5e81ac fg:#88c0d0)"
style = "fg:#2e3440 bg:#88c0d0"

[time]
disabled = false
format = "[ ïº $time ]($style)"
style = "fg:#2e3440 bg:#5e81ac"
time_format = "%H:%M"
