#=============
# === nord ===
#=============

"$schema" = 'https://starship.rs/config-schema.json'

# === Main Prompt Format ===
format = """
$os$username$hostname$directory$git_branch$git_status$python$cmd_duration$jobs$time$line_break$character
"""

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[hostname]
ssh_only = false
format = "[$ssh_symbol@$hostname]($style)"
ssh_symbol = "î¬ "
style = "fg:#2e3440 bg:#5e81ac"

[os]
disabled = false
style = "fg:#2e3440 bg:#5e81ac"

[os.symbols]
Arch = 'ïŒƒ '
Ubuntu = "ó°•ˆ"
Macos = "î˜Ÿ"
Linux = "ó°Œ½"

[directory]
style = "fg:#2e3440 bg:#81a1c1"
read_only = "î©µ"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"
format = "[ ó°‰‹ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï’˜"
"Music" = "ó°š"
"Pictures" = "ï€¾"

[git_branch]
symbol = "ó°˜¬ "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#2e3440 bg:#88c0d0"

[git_status]
style = "fg:#2e3440 bg:#88c0d0 bold"
format = "[ $all_status$ahead_behind ]($style)"
conflicted = "âš¡$count"
ahead      = "â‡¡$count"
behind     = "â‡£$count"
diverged   = "â§–$count"
untracked  = "â€¦$count"
stashed    = "ğŸ“¦$count"
modified   = "âœ$count"
staged     = "âœ”$count"
renamed    = "âœ$count"
deleted    = "âœ–$count"

[python]
symbol = 'ó°Œ  '
format = "[ $symbol$virtualenv ]($style)"
style = "fg:#2e3440 bg:#8fbcbb"

[cmd_duration]
min_time = 5
format = "[ ó°”š $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[jobs]
disabled = false
format = "[ $symbol$number ]($style)"
style = "fg:#2e3440 bg:#88c0d0"

[time]
disabled = false
format = "[ ïº $time ]($style)"
style = "fg:#2e3440 bg:#5e81ac"
time_format = "%H:%M"

[character]
success_symbol = "[ï²](bold fg:#a3be8c)"
error_symbol   = "[ï²](bold fg:#bf616a)"

vimcmd_symbol = "[ î˜« ï²](bold fg:#a3be8c)"
vimcmd_replace_one_symbol = "[ î˜« ï´](bold fg:#ebcb8b)"
vimcmd_replace_symbol = "[ î˜« ï´](bold fg:#d08770)"
vimcmd_visual_symbol = "[ î˜« ï´](bold fg:#b48ead)"
